dist: bionic

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: true

before_install:
  # Install OpenFoam
  - sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
  - add-apt-repository http://dl.openfoam.org/ubuntu
  - apt-get update
  - apt-get -y install openfoam7
  - source /opt/openfoam7/etc/bashrc

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest