dist: bionic

language: python

os: linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  # Install OpenFoam
  - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
  - sudo add-apt-repository http://dl.openfoam.org/ubuntu
  - sudo apt-get update
  - sudo apt-get -y install openfoam7
  - source /opt/openfoam7/etc/bashrc

install:
  - python -m pip install flake8
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest
  - flake8 --max-line-length=100 --show-source HexMeshCylinders